### ISSUE TITLE
Evil Female Ghost Needed

### ISSUE THREAD

**Issue by Bryan-Legend** [L0G1C/laugh-track#1]
This is really great!

Can you please add an evil female ghost for Belcorra?

https://app.demiplane.com/nexus/pathfinder2e/creatures/belcorra-haruvex
https://pathfinderwiki.com/wiki/Belcorra_Haruvex

**Comment by L0G1C** [comment]
I actually had to bust out some Delay and Reverb for this one. Look for it in version 1.1 😄
